---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-intensive-app
  namespace: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-intensive-app
  template:
    metadata:
      labels:
        app: cpu-intensive-app
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: cpu-intensive-app
        image: europe-west8-docker.pkg.dev/opendraw/opendraw-ita-repo/cpu-instensive-app:v60
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
        ports:
        - containerPort: 8000
          name: metrics
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cpu-intensive-app
  namespace: fastapi-app
spec:
  selector:
    app: cpu-intensive-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: metrics
  type: LoadBalancer