apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: fastapi-app-monitoring
  namespace: fastapi-app
spec:
  selector:
    matchLabels:
      app: cpu-intensive-app  # Ensure this label matches your deployment labels
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
